<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.x1aohei</groupId>
        <artifactId>zeus-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>zeus-data-exchange</artifactId>
    <name>zeus-data-exchange</name>


    <dependencies>
        <dependency>
            <groupId>io.github.x1aohei</groupId>
            <artifactId>zeus-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.x1aohei</groupId>
            <artifactId>zeus-task</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
        </dependency>
        <!-- data-exchange-core/pom.xml -->
        <!-- 1. 核心库：包含 BaseMapper、分页等核心功能 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-core</artifactId>
            <scope>provided</scope> <!-- 关键！表示由使用者提供 -->
        </dependency>

        <!-- 2. 注解库：包含 @TableName, @TableId 等 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-annotation</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- data-exchange-core/pom.xml -->
        <!-- MyBatis-Plus 扩展模块，包含 ServiceImpl -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring</artifactId>
        </dependency>

        <!-- 3. 其他必要依赖，如 Spring JDBC（用于 JdbcTemplate） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

</project>
